import {readFileSync,writeFileSync,existsSync,readdirSync} from 'node:fs';
const d=JSON.parse(readFileSync('docs/performance/measurements.json'));
const median=values=>{const a=values.filter(Number.isFinite).sort((x,y)=>x-y);return a.length?a.length%2?a[(a.length-1)/2]:(a[a.length/2-1]+a[a.length/2])/2:null;};
const fmt=x=>x==null?'—':typeof x==='number'?x.toLocaleString('pt-BR',{maximumFractionDigits:1}):String(x).replaceAll('|','/').replace(/\r?\n/g,' ');
const table=(headers,rows)=>'| '+headers.join(' | ')+' |\n|'+headers.map(()=> '---').join('|')+'|\n'+rows.map(r=>'| '+r.map(fmt).join(' | ')+' |').join('\n')+'\n';
const nav=d.samples.filter(x=>x.mode==='navigation'&&x.trial>0&&x.name!=='Boot');
const sample=(name,profile='large')=>nav.find(x=>x.name===name&&x.profile===profile&&x.cache==='cold-session');
const series=(name,profile='large',cache='cold-session')=>d.navigation.find(x=>x.name===name&&x.profile===profile&&x.cache===cache);
const profile=d.samples.filter(x=>x.mode==='profile'&&x.trial>0);
const diagnostics=d.samples.filter(x=>x.mode==='diagnostic');
const slow=d.navigation.filter(x=>!x.name.startsWith('Entrada')&&Number.isFinite(x.medianMs)).toSorted((a,b)=>b.medianMs-a.medianMs)[0];
const most=nav.toSorted((a,b)=>b.documents-a.documents)[0];
const jsonLink='[Amostras e contadores](measurements.json)';
const normalComplete=nav.filter(r=>!r.censored).length;
const normalCensored=nav.filter(r=>r.censored).length;
let report=`# Baseline real de performance — etapa 5\n\nSomente medição. Nenhuma query, cache, rota, arquitetura, asset, memoização ou bug de produção foi alterado. As etapas 1–4 permanecem preservadas no [relatório de testes](../testing/implementation-report.md).\n\n## Resultado principal\n\nA navegação com maior mediana foi **${slow?.name}**, perfil **${slow?.profile}**, **${slow?.cache}**: **${fmt(slow?.medianMs)} ms**. A maior entrega de documentos em uma navegação foi **${fmt(most?.documents)}**, em **${most?.name}**, perfil **${most?.profile}**. Documentos aqui são entregas ao código, não leituras faturadas.\n\n${jsonLink}; [critérios, unidades e limitações](methodology.md); [comandos e ferramentas](../../tests/performance/README.md).\n\n## Ambiente\n\n`;
report+=table(['Item','Configuração'],[['Máquina','AMD Ryzen 7 1700; 8 núcleos/16 threads; 17.123.434.496 bytes RAM'],['Sistema','Windows 10 Pro 10.0.19045'],['Node',d.browser.node],['Navegador',`Chrome ${d.browser.browser}, headless; Playwright 1.55.1`],['Viewport','390 × 844; DPR 1; isMobile e touch; pt-BR; America/Sao_Paulo'],['Build','Vite 5.4.9 production; React 18.3.1; cópias isoladas navigation/profile'],['Firebase','SDK 12.1.0; CLI 14.12.0; Firestore Emulator 1.19.8; Auth Emulator; JRE 21 local'],['Projeto','demo-career-tracker-integration; hosts 127.0.0.1'],['Rede','Loopback sem throttling; HTTP sem compressão de transporte; cache HTTP habilitado'],['Externos','CSP + proxy sem saída + bloqueio DNS; fonte Google bloqueada; token sintético; sem uploads'],['Amostragem','Pequeno/médio: 5 por condição + aquecimento. Grande: saturação censurada. Profiling pequeno/médio: 3 + 1 aquecimento. p95 omitido: n < 20']]);
report+='\nO relógio não simula hardware móvel: o viewport é móvel e a CPU é a máquina acima. A instrumentação tem custo, especialmente observação de DOM e React Profiler. Não extrapolar os tempos locais para latência de produção.\n\n## Perfis de dados\n\n';
report+=table(['Perfil','Carreiras','Temporadas','Partidas','Jogadores/documentos','playerStats','Base/jogadores','Base/torneios','Tabela','Grupos','Docs totais'],d.fixtures.map(f=>[f.name,f.totals.careers,f.totals.seasons,f.totals.matches,f.totals.players,f.totals.playerStats,f.totals.academyPlayers,f.totals.academyTournaments,f.totals.table,f.totals.groups,f.totals.documents]));
report+='\nCada perfil possui três carreiras; uma individual e duas no mesmo grupo. Pequeno: uma temporada por carreira, 20 partidas, elenco de 18; médio: duas temporadas, 50 partidas/temporada, elenco de 25; grande: seis temporadas, 50 partidas/temporada, elenco de 28. Onze fichas por partida finalizada. Os jogadores reaparecem por temporada; a coluna conta documentos de elenco, não pessoas únicas. Há dois torneios de base em andamento por temporada. SHA-256 de cada fixture no JSON, normalizando apenas o UID sintético.\n\n## Navegação\n\nTempos em ms, clique/gesto até destino utilizável. Preparação de modais fica fora da janela; os 400 ms de estabilização ficam fora do tempo utilizável. Cold significa sessão nova; depois da entrada, as rotas dessa sessão já podem reutilizar assets. Warm repete a cadeia com cache HTTP preservado. Nenhuma das colunas afirma que todas as queries vieram de cache.\n\n';
report+=table(['Fluxo','Perfil','Condição','Completas','Censuradas','Mediana','p75','p95','Principal custo observado'],d.navigation.map(x=>[x.name,x.profile,x.cache,x.nComplete,x.nCensored,x.medianMs,x.p75Ms,x.p95Ms,x.nCensored?'CENSURADO no limite de 30 s; duração final desconhecida':x.name.includes('aba')?'Animação Swiper + render':x.name.startsWith('Entrada')?'3 gestos + pausas do script':x.queriesMedian>60?'Hidratação de histórico / N+1':x.name.includes('troféus')?'Abertura de modal / imagens':x.name.includes('Group')?'Buscas de grupo + render':'Dados locais / render']));
report+='\n### Séries preservadas e cobertura efetiva\n\n';
report+=table(['Modo','Perfil','Condição','Cadeias completas','Censuradas','Interrompidas','Aquecimentos'],Object.values(Object.groupBy(d.series.filter(s=>['navigation','profile'].includes(s.mode)),s=>[s.mode,s.profile,s.cache].join('|'))).map(rs=>[rs[0].mode,rs[0].profile,rs[0].cache,rs.filter(s=>s.trial>0&&s.complete).length,rs.filter(s=>s.trial>0&&s.censored).length,rs.filter(s=>s.trial>0&&s.interrupted).length,rs.filter(s=>s.trial===0).length]));
const cut=nav.filter(r=>r.censored);
if(cut.length){report+='\nLimite de observação: 30 s. As contagens abaixo são parciais até o corte. O corte pode ocorrer durante estabilização após conteúdo parcial; não equivale automaticamente a 30 s de página totalmente vazia. Nenhuma duração final foi imputada. O aquecimento e pelo menos duas sessões independentes confirmaram a saturação; o excedente já persistido foi conservado, sem novas repetições do login após a mudança de método solicitada.\n\n';report+=table(['Perfil','Condição','Repetição','Fluxo','Janela ms','Operações iniciadas','Leituras concluídas','playerStats iniciadas/concluídas','Docs','HTTP Firestore','Listeners abertos','Interface utilizável','Estágio'],cut.map(r=>[r.profile,r.cache,r.trial,r.name,r.timings.observedEndMs,r.queries,r.completedReads,`${r.byCategory.playerStats||0}/${r.completedByCategory.playerStats||0}`,r.documents,r.network.firestoreRequests,r.listenersOpened,r.ui.usable?'sim':'não',r.ui.spinner?'spinner principal':r.ui.text?.slice(0,80)||'sem marcador de conteúdo utilizável']));}
const unreachable=Object.entries(Object.groupBy(d.series.filter(s=>s.missingFlows.length),s=>[s.mode,s.profile,s.cache].join('|')));
if(unreachable.length){report+='\nFluxos não alcançados porque uma origem/preparação anterior não terminou no limite:\n\n';report+=table(['Série','Cadeias afetadas (inclui aquecimento)','Fluxos não alcançados'],unreachable.map(([key,rs])=>[key,rs.length,[...new Set(rs.flatMap(r=>r.missingFlows))].join('; ')]));}
report+='\nAs 12 cadeias pequenas de 22/09 e o aquecimento cold médio foram mantidos. As demais séries foram retomadas em 23/09 após reiniciar os emuladores. A varredura de estabilização do coletor foi simplificada para remover custo quadrático do instrumento. Portanto, use a curva entre perfis principalmente para comparar contagens estruturais; dia, estado dos emuladores e custo do coletor também afetam os tempos. Uma cadeia warm precedida de cold censurado tem cache parcialmente preparado, explicitado pela cobertura acima.\n';
report+='\n### Marcos da navegação (medianas das sessões novas, por perfil)\n\n';
const names=[...new Set(nav.map(x=>x.name))];
report+=table(['Perfil','Fluxo','URL/documento','Primeiro texto DOM','Utilizável','Última leitura','Fim da coleta'],d.fixtures.flatMap(f=>names.map(name=>{const rs=nav.filter(x=>x.name===name&&x.profile===f.name&&x.cache==='cold-session');return[f.name,name,...['urlMs','firstContentMs','usableMs','lastDataMs','observedEndMs'].map(key=>key==='usableMs'&&rs.some(x=>x.censored)?null:median(rs.map(x=>x.timings[key])))];})));
report+='\nO primeiro texto é um marcador DOM aproximado, não FCP por rota. Em reload, “URL/documento” é o início do documento novo. Rede, React e assets se sobrepõem: seus tempos não são somados como fases exclusivas. Os eventos mantêm timestamps absolutos para inspeção.\n\n## Dados e Firebase\n\nUma amostra representativa por fluxo e perfil; contagens de cada repetição estão no JSON. “Consultas” inclui registro de listener; “leituras” na saída do runner conta getDoc/getDocs.\n\n';
report+=table(['Perfil','Fluxo','Censurada','Operações lógicas','Carreiras','Temporadas','Jogadores','Partidas','playerStats','Tabela','Base','Grupos','Docs entregues','HTTP Firestore','Operações repetidas'],d.fixtures.flatMap(f=>names.map(name=>{const r=sample(name,f.name);if(!r)return[];const c=r.byCategory;return[f.name,name,r.censored?'sim':'não',r.queries,c.careers||0,c.seasons||0,c.players||0,c.matches||0,c.playerStats||0,c.table||0,(c.academyPlayers||0)+(c.academyTournaments||0),c.groups||0,r.documents,r.network.firestoreRequests,r.duplicateOperations];})).filter(x=>x.length));
report+='\nAs temporadas vêm embutidas no documento da carreira nos fluxos medidos; zero queries da coleção `seasons` não significa zero temporadas processadas. Firestore multiplexa operações em WebChannel. Entregas repetidas de documentos podem compartilhar cache/target do SDK, portanto os números não estimam cobrança.\n\n### N+1 e duplicações\n\n';
report+=table(['Perfil','Partidas na fixture','playerStats ao abrir Careers','playerStats ao abrir Match','playerStats ao abrir Player','Docs ao abrir Player'],d.fixtures.map(f=>{const a=sample('Login → CareersPage',f.name),m=sample('Season → Match',f.name),p=sample('Season → Player',f.name);return[f.name,f.totals.matches,a?.byCategory.playerStats,m?.byCategory.playerStats,p?.byCategory.playerStats,p?.documents];}));
report+=table(['Partidas','playerStats iniciadas no login','Concluídas na janela representativa','Relação'],d.fixtures.map(f=>{const r=sample('Login → CareersPage',f.name);return[f.totals.matches,r?.byCategory.playerStats,r?.completedByCategory.playerStats,`${fmt((r?.byCategory.playerStats||0)/f.totals.matches)} por partida${r?.censored?' (censurado)':''}`];}));
report+='\nMEDIDO: M partidas iniciam M buscas adicionais de playerStats, além de consultas de partidas/elencos e inscrição de carreiras. CONFIRMADO PELO CÓDIGO: a busca individual ocorre no percurso de cada partida. No grande, quantidade iniciada não significa quantidade concluída.\n\n### Grande com autenticação preparada\n\nEsta coleta exploratória autentica pela UI, encerra a hidratação inicial ao abrir Tutorial e então acessa URLs diretamente com Auth/cache HTTP preservados. Não é a jornada cold original nem uma sessão com histórico integralmente carregado. n = 1 por alvo, sem percentis. Academy depende de location.state produzido pela temporada; sua abertura direta equivalente não foi medida no grande.\n\n';
report+=table(['Alvo','Estado','Observado ms','Utilizável ms','Leituras iniciadas/concluídas','playerStats iniciadas/concluídas','Docs','HTTP Firestore','Listeners abertos','Documento novo'],diagnostics.filter(r=>r.name.startsWith('Grande preparado:')).map(r=>[r.name,r.censored?'CENSURADO':'MEDIDO',r.timings.observedEndMs,r.timings.usableMs,`${r.reads}/${r.completedReads}`,`${r.byCategory.playerStats||0}/${r.completedByCategory.playerStats||0}`,r.documents,r.network.firestoreRequests,r.listenersOpened,r.timings.newDocumentMs!=null?'sim':'não']));
report+='\nA abertura direta do grupo tem um custo que não aparece no clique SPA com location.state: ServiceCareerGroup.getById hidrata as duas carreiras pelo Getters antes das duas buscas de PlayersGroupService. No grande preparado foram medidas 600 buscas de playerStats nesse caminho, além do percurso duplicado do grupo. Não se atribui toda a diferença de tempo ao reload: também muda o estado de entrada e o trabalho realizado. O Player preparado iniciou 1.800 buscas de stats; essa contagem é parcial de uma observação censurada, não duração final nem previsão de cobrança.\n';
report+='\n`Getters` carrega partidas e fichas de todas as carreiras/temporadas até para uma rota específica. `usePlayerPageData` instancia `useCareers` diretamente e via `useSeasonView`: a instrumentação registra duas inscrições e duas hidratações. `useMatchData` busca novamente a subcoleção de fichas da partida já carregada. No grupo, `getAggregatedGroupStats` e `getGroupSeasonsData` repetem o mesmo percurso; contagens e caminhos duplicados estão no JSON. Isso indica candidatos a deduplicação futura, sem implementá-la aqui.\n\n## Listeners e updatedAt\n\nCiclos reais SPA Careers → Group → Careers, sem reload entre os ciclos. Contagens se referem a inscrições da aplicação no documento atual; não a conexões físicas do SDK.\n\n';
report+=table(['Perfil','Evento','Ciclo','Listeners antes','Listeners depois','Delta','Callbacks','Operações','Docs'],diagnostics.filter(x=>x.name.includes('Listener:')||x.name.startsWith('updatedAt:')).map(x=>[x.profile,x.name,x.cycle??'—',x.listenersBefore?.firestore,x.listenersAfter?.firestore,x.listenersBefore&&x.listenersAfter?x.listenersAfter.firestore-x.listenersBefore.firestore:null,x.callbacks,x.queries,x.documents]));
report+='\nO callback de autenticação de `useCareers` devolve o cleanup ao SDK Auth; isso não registra o cleanup do listener Firestore no efeito React. Os ciclos quantificam o efeito sem corrigir o hook. A atualização de apenas `updatedAt` permite observar trabalho mesmo sem alteração de partidas, jogadores ou tabela. Reload destrói o documento e reinicia suas inscrições; a contagem não é acumulada indevidamente entre documentos.\n\n## React Profiler\n\nBuild `react-dom/profiling`, separado dos tempos normais. As medianas usam execuções concluídas, com n explícito; fluxos censurados não entram nesta tabela de duração. Maior render é o máximo observado nas execuções, não a duração completa de commit DOM. Duração acumulada é soma de `actualDuration` **dentro da mesma fronteira**; não somar linhas de pais e filhos. Callbacks em múltiplas instâncias de CareerCard são agregados.\n\n';
const reactGroups={};for(const row of profile.filter(x=>!x.censored))for(const [component,v] of Object.entries(row.react)){const key=row.profile+'|'+row.name+'|'+component;(reactGroups[key]??=[]).push({...v,profile:row.profile,flow:row.name,component});}
report+=table(['Perfil','Fluxo','Componente','n','Callbacks de commit (mediana)','Render acumulado ms (mediana)','Maior render observado ms'],Object.values(reactGroups).map(rs=>[rs[0].profile,rs[0].flow,rs[0].component,rs.length,median(rs.map(x=>x.commits)),median(rs.map(x=>x.totalMs)),Math.max(...rs.map(x=>x.maxMs))]).sort((a,b)=>b[5]-a[5]));
report+='\n### Atualização sem mudar o conteúdo esportivo\n\n';
report+=table(['Perfil','Atualização','Componente','Callbacks','Render acumulado ms','Máximo ms'],diagnostics.filter(r=>r.name==='updatedAt: Season com abas ocultas').flatMap(r=>Object.entries(r.react).map(([component,v])=>[r.profile,r.name,component,v.commits,v.totalMs,v.maxMs])));
report+='\n### Abas montadas antes da visita\n\n';
report+=table(['Perfil','Fluxo','Componentes montados na janela','Slides no DOM','Slides inativos','Nós DOM'],d.fixtures.flatMap(f=>['Career → Season','Season → Match','Season → Academy'].map(name=>{const r=sample(name,f.name);return[f.name,name,r?.mounted.join(', '),r?.snapshot?.slides.length,r?.snapshot?.slides.filter(x=>!x.active).length,r?.snapshot?.nodes];})));
report+='\nSectionView e Match montam as abas do Swiper de uma vez. A tabela inicia uma leitura enquanto “Elenco” está ativa; as demais abas calculam/renderizam seus conteúdos. Na Academy, o dashboard apresenta vários cards simultaneamente e o modo de detalhe é condicional, não um Swiper de todas as telas. Custos por componente e mudanças de aba estão medidos acima. Re-render, isoladamente, não prova desperdício; a atualização diagnóstica de `updatedAt` fornece um caso de conteúdo esportivo inalterado. Não foi feito um contrafactual de montagem sob demanda nem uma prova geral de irrelevância de todas as mudanças de props.\n\n## Bundle\n\n';
report+=table(['Item','Bytes','gzip bytes'],[...d.bundle.chunks.map(x=>[x.file,x.bytes,x.gzip]),...d.bundle.css.map(x=>[x.name,x.bytes,x.gzip])] );
report+=`\n${d.bundle.chunks.length} chunk JS; ${d.bundle.chunks.reduce((a,x)=>a+x.dynamicImports.length,0)} imports dinâmicos no grafo emitido. O arquivo tem **5.256.697 bytes**; o valor 5.210,41 kB impresso pelo Vite não era uma contagem física exata de bytes UTF-8. O gzip confirma 1.678.953 bytes. Não houve splitting ou compressão de assets.\n\n`;
report+=table(['Módulo','renderedLength do Rollup (pré-minificação final)'],d.bundle.chunks.flatMap(x=>x.largestModules).slice(0,12).map(x=>[x.id,x.renderedLength]));
report+=`\nreact-world-flags: ${fmt(d.bundle.flagsRenderedLength)} em renderedLength, ${fmt(d.bundle.flagsRenderedShare*100)}% da soma nessa mesma unidade. Foram encontrados ${d.bundle.flagUriCount} data URIs de bandeiras; ${fmt(d.bundle.flagPayloadBytes)} bytes desses payloads permanecem literalmente no JS final (${fmt(d.bundle.flagPayloadShare*100)}% do arquivo). Esse último número é um piso atribuível aos payloads; não inclui toda a lógica da biblioteca. Não confundir renderedLength com bytes minificados ou contribuição gzip independente.\n\n## Assets\n\nMaiores arquivos originais de troféus; inventário não implica que todos foram baixados nas jornadas.\n\n`;
report+=table(['Arquivo','Bytes originais','Dimensões'],d.assets.slice(0,12).map(x=>[x.path,x.bytes,x.width?`${x.width} × ${x.height}`:'—']));
const logo=readFileSync('public/Logo.png');
report+=`\nA fixture reutiliza /Logo.png como escudo/logo de liga: ${fmt(logo.length)} bytes, ${logo.readUInt32BE(16)} × ${logo.readUInt32BE(20)} px. Isso reduz a diversidade de downloads em comparação com escudos reais distintos. O custo de todas as imagens do inventário não é somado ao carregamento de uma tela que não as requisitou.\n`;
report+=table(['Perfil','Tela (cold, repetição 1)','Recursos de imagem concluídos','Bytes transferidos','Elementos img no DOM'],d.samples.filter(r=>r.mode==='navigation'&&r.trial===1&&r.cache==='cold-session').map(r=>[r.profile,r.name,r.network.images.length,r.network.images.reduce((a,x)=>a+x.transferSize,0),r.snapshot?.images.length]));
const trophyLoads=nav.filter(x=>x.trial===1).flatMap(r=>r.network.images.filter(x=>x.name.includes('/trophies/')).map(img=>({r,img})));
report+='\nTransferências observadas de troféus por perfil, primeira repetição. Zero de transferência indica cache local; não é tamanho original zero.\n\n';
report+=table(['Perfil','Fluxo','Condição','Arquivo','Transferência','Corpo','Resource Timing ms','Natural','Exibição px'],trophyLoads.map(({r,img})=>{const dim=r.snapshot?.images.find(x=>x.src===img.name);return[r.profile,r.name,r.cache,new URL(img.name).pathname,img.transferSize,img.encodedBodySize,img.duration,dim?`${dim.naturalWidth} × ${dim.naturalHeight}`:'—',dim?`${fmt(dim.width)} × ${fmt(dim.height)}`:'—'];}));
report+='\nResource Timing mede a duração do recurso, não o atraso causal que ele acrescentou ao conteúdo utilizável. Imagens repetidas no DOM podem reutilizar uma única transferência. O JSON conserva contagens e dimensões por tela, inclusive assets locais que não são troféus.\n\n## Main thread e long tasks\n\nMaiores tarefas da série de navegação normal; profiling excluído.\n\n';
const tasks=d.samples.filter(r=>r.mode==='navigation'&&r.trial>0).flatMap(r=>r.longTasks.map(t=>({...t,flow:r.name,profile:r.profile,cache:r.cache,trial:r.trial}))).sort((a,b)=>b.duration-a.duration);
report+=table(['Fluxo','Perfil','Condição','Repetição','Início relativo ms','Duração ms'],tasks.slice(0,15).map(x=>[x.flow,x.profile,x.cache,x.trial,x.startMs,x.duration]));
if(d.trace){const trace=d.trace;report+=`\nTrace adicional de atribuição, uma execução do perfil ${trace.profile} (login + Geral + Partidas). Categorias podem ser aninhadas; não somar como CPU exclusiva.\n\n`;const selected=trace.events.filter((x,i)=>i<16||['V8.ParseProgram','V8.ParseFunction','Decode Image'].includes(x.name));report+=table(['Evento Chromium','Ocorrências','Tempo acumulado ms','Maior ocorrência ms'],selected.map(x=>[x.name,x.count,x.totalMs,x.maxMs]));report+='\nDecode Image é o custo observado nessa thread/captura; não foi associado individualmente a cada troféu nem inclui necessariamente todo decode feito em threads auxiliares. RunMicrotasks inclui trabalho de SDK/aplicação/instrumentação; não há atribuição exclusiva por função nesse trace.\n';}
report+='\nNão se atribui toda long task a React ou à rede. Parsing/execução do JS, layout/paint e decodificação só são separados quando o trace expõe a categoria. As fronteiras React atribuem render às listas/abas; elas não isolam todo cálculo fora do render. Os benchmarks de CPU anteriores não foram reexecutados ou substituídos. Não foi localizado artefato separado desses benchmarks no checkout; os relatórios anteriores permanecem intactos.\n\n## Web Vitals (laboratório)\n\n';
const vitals=new Map();for(const row of d.samples.filter(x=>x.mode==='navigation'&&x.trial>0))for(const v of row.vitals)vitals.set(v.id+'|'+v.name,{...v,profile:row.profile,cache:row.cache});
report+=table(['Perfil','Condição','Métrica','Documentos com valor','Mediana','Máximo'],d.fixtures.flatMap(f=>['cold-session','warm-session'].flatMap(cache=>['FCP','LCP','CLS','INP'].map(name=>{const xs=[...vitals.values()].filter(v=>v.profile===f.name&&v.cache===cache&&v.name===name).map(v=>v.value);return[f.name,cache,name,xs.length,median(xs),xs.length?Math.max(...xs):null];}))));
report+='\nFCP/LCP/INP em ms; CLS sem unidade. São valores observados por documento na sequência automatizada, não distribuição de usuários nem certificação de Core Web Vitals. Documentos SPA compartilham a mesma janela; zero valores capturados é mostrado como ausência, nunca como aprovação. INP depende das interações feitas e LCP encerra sua observação com interação; comparar somente sequências equivalentes.\n\n## Performance percebida, reload e timers\n\n';
report+=table(['Perfil (cold)','Fluxo','Documentos novos','Bundles requisitados','Bytes JS transferidos','Callbacks Auth modular','Queries','Utilizável ms'],d.fixtures.flatMap(f=>['CareersPage → Career','Career → Season','Career → Geral','Season → Match','Geral → ComparePlayers'].map(name=>{const r=sample(name,f.name);return[f.name,name,r?r.timings.newDocumentMs!=null?1:0:null,r?.network.scripts.length,r?.network.scripts.reduce((a,x)=>a+x.transferSize,0),r?.authCallbacks,r?.queries,series(name,f.name)?.medianMs];})));
report+='\nAs recargas atuais reexecutam o bundle e reinicializam Auth/listeners mesmo quando os bytes vêm do cache. Não foi implementada uma rota alternativa para um teste A/B; a tabela compara trajetos que já existem e têm trabalhos diferentes. Portanto a diferença bruta não é toda causada pelo reload.\n\n';
report+=table(['Perfil','Comparação: primeiro texto ms','Comparação utilizável ms','Timer','Atraso real mediano ms','Timers disparados'],d.fixtures.flatMap(f=>[500,1500].map(delay=>{const rs=nav.filter(r=>r.name==='Geral → ComparePlayers'&&r.profile===f.name&&r.cache==='cold-session');const timers=rs.flatMap(x=>x.timers).filter(x=>x.delay===delay&&Number.isFinite(x.actualDelayMs));return[f.name,median(rs.map(x=>x.timings.firstContentMs)),median(rs.map(x=>x.timings.usableMs)),delay,median(timers.map(x=>x.actualDelayMs)),timers.length];})));
report+='\nColeta diagnóstica adicional espera os dados e mais 700 ms, para observar o timer de 500 ms mesmo quando fora do caminho crítico. Estes valores não integram o baseline de navegação.\n\n';
report+=table(['Perfil','Repetição','Timer ms','Agendado após início ms','Disparado após início ms','Atraso real ms'],diagnostics.filter(r=>r.name==='Compare: timers até depois dos dados').flatMap(r=>r.timers.map(t=>[r.profile,r.trial,t.delay,t.scheduledMs,t.firedMs,t.actualDelayMs])));
report+=table(['Perfil','Seleção','Repetição','Utilizável ms','Consultas','Render ComparePlayers ms'],diagnostics.filter(r=>r.name.startsWith('Compare: selecionar')).map(r=>[r.profile,r.name,r.trial,r.timings.usableMs,r.queries,r.react.ComparePlayers?.totalMs]));
report+='\nO timer de 1500 ms pode liberar uma interface ainda sem os jogadores carregados. O de 500 ms é agendado quando chegam carreiras; se o fallback já liberou o loading, ele não acrescenta automaticamente 500 ms ao caminho crítico. As amostras permitem distinguir agendamento, disparo e disponibilidade dos dados. Não se somam 500 + 1500 como atraso obrigatório.\n\n### useMatchActions: leitura antes de loading\n\n';
const action=diagnostics.filter(r=>r.name.startsWith('Salvar partida')&&r.trial<=3);
report+=table(['Perfil','Repetição','Clique → estado saving ms','Clique → spinner ms','Spinner → utilizável ms','Leituras antes de saving','Consultas','Docs','Retorno utilizável ms','Última leitura ms'],action.map(r=>[r.profile,r.trial,r.timings.savingStateMs,r.timings.firstSpinnerMs,r.timings.usableMs-r.timings.firstSpinnerMs,r.timings.readsBeforeSaving,r.queries,r.documents,r.timings.usableMs,r.timings.lastDataMs]));
report+='\nAs 686 leituras por salvamento são o trabalho acumulado na janela inteira: a interface volta em aproximadamente 2,5 s, mas leituras de atualização continuam até aproximadamente 20–21 s. O término do spinner não equivale ao fim de todo o trabalho de dados.\n';
report+='\nSérie principal limitada às três primeiras amostras válidas. Quando a última orientação chegou, as amostras 4 e 5 já estavam persistidas; foram conservadas como suplementares no JSON, sem executar novos salvamentos e sem incluí-las nas medianas principais.\n';
report+='\nA ação usa adversário novo para exercitar a busca de histórico anterior a `setIsSaving(true)`. A escrita ocorre somente no emulador e é removida entre repetições. O marcador de ativação do estado e o spinner observável ficam nos eventos brutos. O spinner substitui o formulário inteiro.\n\n## Gargalos e próxima etapa\n\n<!-- findings -->\n\n## Validações e integridade\n\n<!-- validation -->\n\n## Cobertura do pedido\n\nAs 28 seções foram rastreadas: escopo/isolamento (1–2), fixtures (3), jornadas e marcos (4–6), Firebase/N+1/duplicações (7–9), listeners (10), Profiler/abas/main thread (11–13), vitals (14), bundle/bandeiras/assets (15–17), percepção/reload/timers/salvamento (18–21), preservação de benchmarks e produção/bugs (22–24), relatório/reprodução/validações/resumo (25–28). Limitações técnicas são declaradas na seção correspondente; métricas não observáveis não receberam valores inventados.\n';
const n1=d.fixtures.map(f=>`${f.totals.matches} partidas → ${sample('Login → CareersPage',f.name)?.byCategory.playerStats??'não observado'} buscas iniciadas`).join('; ');
const player=nav.filter(r=>r.name==='Season → Player'&&!r.censored).toSorted((a,b)=>b.queries-a.queries)[0];
const listener=diagnostics.filter(r=>r.name==='updatedAt: depois dos ciclos'&&!r.censored).toSorted((a,b)=>b.queries-a.queries)[0];
const listenerBefore=diagnostics.find(r=>r.profile===listener?.profile&&r.name==='updatedAt: antes dos ciclos');
const findingsRows=[
  ['P0','Hidratação global + N+1: '+n1,'A espera por uma página depende do histórico inteiro; grande censurado no limite local','Carregar o escopo necessário e planejar agregação/busca das estatísticas','Dados legados embutidos, invalidação e consistência dos totais'],
  ['P1',`Player (${player?.profile}): ${player?.reads} getDoc/getDocs + ${player?.listenersOpened} inscrições; ${player?.byCategory.playerStats} buscas de stats; ${player?.documents} documentos entregues`,'Duas instâncias de useCareers reidratam o mesmo histórico','Compartilhar uma fonte de dados entre useSeasonView e usePlayerPageData','Ciclo de vida, estado de loading, rotas de grupo e jogador'],
  ['P0',`Listeners (${listener?.profile}): ${listenerBefore?.listenersBefore?.firestore} → ${listener?.listenersAfter?.firestore}; updatedAt provoca ${listenerBefore?.queries} → ${listener?.queries} operações`,'Trabalho de hidratação cresce após sair e voltar pela SPA','Corrigir o vínculo do cleanup e limitar o escopo do refetch','Corridas de autenticação, callbacks em andamento e assinantes compartilhados'],
  ['P1',`Bundle único ${d.bundle.chunks[0].bytes} bytes; payloads de bandeiras ${d.bundle.flagPayloadBytes} bytes`,'Carga inicial e reexecução em recargas; sem imports dinâmicos','Avaliar divisão por rota e distribuição seletiva de bandeiras','Rotas profundas, loading e compatibilidade visual'],
  ['P1','Reload real em Career e Season: documento, bundle e Auth reiniciados; tabelas acima','Cache de bytes não preserva o estado de memória da aplicação','Avaliar navegação interna depois de estabilizar a camada de dados','Estado da rota, seleção de temporada e dados obsoletos'],
  ['P1','SectionView monta sete slides; Classificação lê a tabela antes da visita; grupo percorre caminhos duas vezes','Trabalho inicial fora da aba ativa; duplicação no grupo','Avaliar montagem sob demanda e compartilhamento de consultas','Estado entre abas e equivalência funcional dos dados'],
  ['P2','Timers de 1.500/500 ms e primeiro texto antes de dados; medições separadas acima','Conteúdo parcial parece pronto; relógio artificial difere do término das leituras','Definir loading pelo estado real dos dados','Evitar flashes e perda de feedback'],
  ['P2',`Salvar (${action[0]?.profile}): mediana ${fmt(median(action.map(r=>r.timings.savingStateMs)))} ms até saving e ${fmt(median(action.map(r=>r.timings.firstSpinnerMs)))} ms até spinner`,'Busca anterior ao feedback; spinner substitui o formulário','Avaliar feedback imediato preservando contexto','Duplo envio, validação e tratamento de erro'],
  ['P2','Troféus em PNG com dimensões e bytes muito acima da exibição; inventário e transferências acima','Transferência inicial e memória de imagem; cache reduz repetições','Avaliar variantes dimensionadas e formatos adequados','Qualidade/transparência e identidade dos troféus'],
];
const findings=table(['Prioridade','Gargalo e evidência','Impacto observado','Hipótese para a próxima etapa','Risco da mudança'],[0,2,4,3,1,5,6,7,8].map(i=>findingsRows[i]));
report=report.replace('<!-- findings -->',findings+'\nOs três primeiros focos são N+1/hidratação global (P0), listeners (P0) e reinicialização com nova hidratação (P1). O reload fica em P1 porque sua parcela causal isolada não foi medida por um teste A/B. P0/P1/P2 expressam prioridade de performance, sem substituir a prioridade dos bugs de integridade das etapas anteriores. Nenhuma hipótese foi implementada. PlayersGroupService não lê playerStats; sua resposta mais rápida não prova equivalência funcional com a hidratação completa. A abertura direta acrescenta a hidratação de ServiceCareerGroup, conforme a tabela de alvos preparados. Não houve validação semântica nova de todos os totais do grupo.\n');
let validation='Validação final ainda não executada nesta coleta.\n';
if(existsSync('docs/performance/validation.json')){
  const v=JSON.parse(readFileSync('docs/performance/validation.json'));
  validation=table(['Comando','Código de saída','Resultado','Conclusão UTC'],v.results.map(r=>[r.command,r.exitCode,r.summary?.join('; ')||'verificação concluída',r.finishedAt]));
  if(v.coverage)validation+=`\nCoverage conjunta: linhas ${v.coverage.lines.pct}%; statements ${v.coverage.statements.pct}%; funções ${v.coverage.functions.pct}%; branches ${v.coverage.branches.pct}%. [Resultados e contadores](validation.json).\n`;
  if(v.productionBuild)validation+='\nBuild de produção recalculado na validação final:\n\n'+table(['Arquivo','Bytes físicos','gzip bytes'],v.productionBuild.map(a=>[a.name,a.bytes,a.gzip]));
  if(v.sourceIntegrity)validation+=`\nSHA-256: ${v.sourceIntegrity.compared} arquivos de src comparados, ${v.sourceIntegrity.changed.length} alterados e ${v.sourceIntegrity.added.length} adicionados na etapa 5. [Evidência de integridade](source-integrity.json). O checkout contém mudanças anteriores do usuário/etapas anteriores; não foram desfeitas e não são atribuídas à etapa 5.\n`;
}
validation+='\nArquivos exclusivos da medição:\n\n'+readdirSync('tests/performance').filter(x=>/\.(mjs|cjs|js|md)$/.test(x)).sort().map(x=>`- [tests/performance/${x}](../../tests/performance/${x})`).join('\n')+'\n- tests/performance-tools/package.json e package-lock.json: dependências isoladas.\n- docs/performance: relatório, metodologia, measurements.json, validation.json e source-integrity.json.\n- docs/testing/implementation-report.md: apenas vínculo e resumo da etapa 5 acrescentados.\n\nEventos brutos, trace comprimido, builds isolados e logs ficam em .test-tools/performance, ignorado pelo Git. O inventário consolidado permite inspecionar as medições sem executar novamente o navegador; a reprodução integral usa os comandos do README.\n';
report=report.replace('<!-- validation -->',validation);
report=report.replace('\n## Performance percebida', '\nNo grande, os vitals capturados no documento inicial descrevem principalmente a entrada/Welcome e as interações alcançadas antes do corte. LCP baixo nessa tela não significa CareersPage utilizável: o login continuou censurado. Valores de laboratório, inclusive CLS/INP zero, não aprovam a experiência de produção. Eventos finais ocorridos fora das janelas registradas podem não estar no consolidado.\n\n## Performance percebida');
report=report.replace('\n## Ambiente',`\nForam preservadas **${normalComplete} janelas normais concluídas** (360 dos fluxos pequeno/médio + 10 entradas do grande), **${normalCensored} janelas normais censuradas**, 20 cadeias normais completas e 6 cadeias medidas de profiling. Há mais 2 censuras nos alvos preparados e 2 nos aquecimentos: **13 censuras válidas no total, 11 excluindo aquecimento**. Uma cadeia grande foi interrompida depois da entrada. As duas seleções inválidas por falha de automação permanecem arquivadas e não integram esses números. Boot e aquecimentos são excluídos da contagem de janelas normais medidas.\n\n## Ambiente`);
report=report.replace('O spinner substitui o formulário inteiro.', 'O spinner substitui o formulário inteiro. A leitura antes de saving foi observada, mas o intervalo até o feedback foi pequeno no emulador local; este cenário não comprova um atraso perceptível sob rede real. Não foi adicionada latência artificial.');
const allCompleted=d.samples.filter(r=>r.trial>0&&!r.censored&&Number.isFinite(r.timings.usableMs)&&r.mode!=='profile').toSorted((a,b)=>b.timings.usableMs-a.timings.usableMs);
if(allCompleted[0])report+=`\nMaior observação pontual concluída, considerando também diagnósticos separados: **${allCompleted[0].name}**, ${allCompleted[0].profile}, ${fmt(allCompleted[0].timings.usableMs)} ms. Isso não substitui o ranking por mediana da série normal nem cria um percentil para n = 1.\n`;
report+='\n## Estado da evidência\n\nMEDIDO significa evento/contador efetivamente capturado. CONFIRMADO PELO CÓDIGO identifica a explicação encontrada no código, sem contrafactual implementado. CENSURADO significa que o limite encerrou a observação sem duração final. NÃO MEDIDO significa ausência de observação válida; não equivale a zero nem a aprovação.\n\n';
report+=table(['Seções do pedido','Estado e referência'],[
  ['1–2: princípio e ambiente','MEDIDO: builds isolados, navegador real e emuladores; nenhuma alteração de produção'],
  ['3: perfis','MEDIDO: manifesto determinístico, volumes exatos e hashes'],
  ['4–6: jornadas e distribuições','MEDIDO pequeno/médio; CENSURADO login grande; demais origens grandes NÃO MEDIDAS, salvo alvos preparados explicitamente separados'],
  ['7–9: Firebase, N+1, duplicações','MEDIDO: início/fim por categoria, HTTP separado, documentos e caminhos; explicação CONFIRMADA PELO CÓDIGO'],
  ['10: listeners','MEDIDO em ciclos SPA dos perfis alcançáveis; cleanup CONFIRMADO PELO CÓDIGO'],
  ['11–12: React e abas','MEDIDO com React Profiler separado; grande não repetido; contrafactual de montagem sob demanda NÃO MEDIDO'],
  ['13: main thread','MEDIDO: long tasks e trace adicional; atribuição causal exclusiva por função NÃO MEDIDA'],
  ['14: vitals','MEDIDO apenas nos documentos com valor; campo ausente é NÃO MEDIDO; métricas de usuários reais NÃO MEDIDAS'],
  ['15–17: bundle, flags e assets','MEDIDO: bytes, gzip, grafo, payloads, dimensões e recursos; economia após otimização NÃO MEDIDA'],
  ['18–21: percepção, reload, timers, saving','MEDIDO: marcos DOM, novo documento, timers e feedback; benefício de correção hipotética NÃO MEDIDO'],
  ['22: benchmarks anteriores','Preservados os arquivos existentes; artefato específico de benchmark de CPU não localizado neste checkout; nenhuma série anterior recriada'],
  ['23–24: produção e bugs','Verificação SHA-256 e diff; nenhuma correção/otimização nesta etapa'],
  ['25–28: entrega, reprodução e validação','Relatório, metodologia, ferramentas, resultados persistidos e validações acima'],
]);
const failures=[...new Set(d.samples.flatMap(r=>r.errors).map(e=>e.message))];
report+='\nErros de página/diálogos capturados: '+(failures.length?failures.map(e=>'`'+e.replaceAll('`','')+'`').join('; '):'nenhum nas janelas consolidadas')+'. Bloqueios esperados de recursos externos não são tratados como acesso bem-sucedido.\n';
writeFileSync('docs/performance/baseline-report.md',report);
console.log('Report generated',report.length,'characters');
